namespace Trader.Model.Glossaries.Providers
{
    using System.Collections.Generic;
    using System.Linq;

    internal class PoviatProvider : IGlossaryProvider<Poviat>
    {
        public IEnumerable<Poviat> GetValues()
        {
            return Poviats;
        }

        private static IEnumerable<Poviat> GetPoviats()
        {
            yield return new Poviat { Id = 1, Name = "bolesławiecki", Province = ProvinceProvider.Get(1), Sanitize = "boleslawiecki", Capital = "0" };
            yield return new Poviat { Id = 2, Name = "dzierżoniowski", Province = ProvinceProvider.Get(1), Sanitize = "dzierzoniowski", Capital = "0" };
            yield return new Poviat { Id = 3, Name = "głogowski", Province = ProvinceProvider.Get(1), Sanitize = "glogowski", Capital = "0" };
            yield return new Poviat { Id = 4, Name = "górowski", Province = ProvinceProvider.Get(1), Sanitize = "gorowski", Capital = "0" };
            yield return new Poviat { Id = 5, Name = "jaworski", Province = ProvinceProvider.Get(1), Sanitize = "jaworski", Capital = "0" };
            yield return new Poviat { Id = 6, Name = "jeleniogórski", Province = ProvinceProvider.Get(1), Sanitize = "jeleniogorski", Capital = "154" };
            yield return new Poviat { Id = 7, Name = "kamiennogórski", Province = ProvinceProvider.Get(1), Sanitize = "kamiennogorski", Capital = "0" };
            yield return new Poviat { Id = 8, Name = "kłodzki", Province = ProvinceProvider.Get(1), Sanitize = "klodzki", Capital = "0" };
            yield return new Poviat { Id = 9, Name = "legnicki", Province = ProvinceProvider.Get(1), Sanitize = "legnicki", Capital = "155" };
            yield return new Poviat { Id = 10, Name = "lubański", Province = ProvinceProvider.Get(1), Sanitize = "lubanski", Capital = "0" };
            yield return new Poviat { Id = 11, Name = "lubiński", Province = ProvinceProvider.Get(1), Sanitize = "lubinski", Capital = "0" };
            yield return new Poviat { Id = 12, Name = "lwówecki", Province = ProvinceProvider.Get(1), Sanitize = "lwowecki", Capital = "0" };
            yield return new Poviat { Id = 13, Name = "milicki", Province = ProvinceProvider.Get(1), Sanitize = "milicki", Capital = "0" };
            yield return new Poviat { Id = 14, Name = "oleśnicki", Province = ProvinceProvider.Get(1), Sanitize = "olesnicki", Capital = "0" };
            yield return new Poviat { Id = 15, Name = "oławski", Province = ProvinceProvider.Get(1), Sanitize = "olawski", Capital = "0" };
            yield return new Poviat { Id = 16, Name = "polkowicki", Province = ProvinceProvider.Get(1), Sanitize = "polkowicki", Capital = "0" };
            yield return new Poviat { Id = 17, Name = "strzeliński", Province = ProvinceProvider.Get(1), Sanitize = "strzelinski", Capital = "0" };
            yield return new Poviat { Id = 18, Name = "średzki", Province = ProvinceProvider.Get(1), Sanitize = "sredzki", Capital = "0" };
            yield return new Poviat { Id = 19, Name = "świdnicki", Province = ProvinceProvider.Get(1), Sanitize = "swidnicki", Capital = "0" };
            yield return new Poviat { Id = 20, Name = "trzebnicki", Province = ProvinceProvider.Get(1), Sanitize = "trzebnicki", Capital = "0" };
            yield return new Poviat { Id = 21, Name = "wałbrzyski", Province = ProvinceProvider.Get(1), Sanitize = "walbrzyski", Capital = "156" };
            yield return new Poviat { Id = 22, Name = "wołowski", Province = ProvinceProvider.Get(1), Sanitize = "wolowski", Capital = "0" };
            yield return new Poviat { Id = 23, Name = "wrocławski", Province = ProvinceProvider.Get(1), Sanitize = "wroclawski", Capital = "157" };
            yield return new Poviat { Id = 24, Name = "ząbkowicki", Province = ProvinceProvider.Get(1), Sanitize = "zabkowicki", Capital = "0" };
            yield return new Poviat { Id = 25, Name = "zgorzelecki", Province = ProvinceProvider.Get(1), Sanitize = "zgorzelecki", Capital = "0" };
            yield return new Poviat { Id = 26, Name = "złotoryjski", Province = ProvinceProvider.Get(1), Sanitize = "zlotoryjski", Capital = "0" };
            yield return new Poviat { Id = 27, Name = "Jelenia Góra m.", Province = ProvinceProvider.Get(1), Sanitize = "jelenia_gora_miasto", Capital = "0" };
            yield return new Poviat { Id = 28, Name = "Legnica m.", Province = ProvinceProvider.Get(1), Sanitize = "legnica_miasto", Capital = "0" };
            yield return new Poviat { Id = 29, Name = "Wałbrzych m.", Province = ProvinceProvider.Get(1), Sanitize = "walbrzych_miasto", Capital = "0" };
            yield return new Poviat { Id = 30, Name = "Wrocław m.", Province = ProvinceProvider.Get(1), Sanitize = "wroclaw_miasto", Capital = "0" };
            yield return new Poviat { Id = 31, Name = "aleksandrowski", Province = ProvinceProvider.Get(2), Sanitize = "aleksandrowski", Capital = "0" };
            yield return new Poviat { Id = 32, Name = "brodnicki", Province = ProvinceProvider.Get(2), Sanitize = "brodnicki", Capital = "0" };
            yield return new Poviat { Id = 33, Name = "bydgoski", Province = ProvinceProvider.Get(2), Sanitize = "bydgoski", Capital = "285" };
            yield return new Poviat { Id = 34, Name = "chełmiński", Province = ProvinceProvider.Get(2), Sanitize = "chelminski", Capital = "0" };
            yield return new Poviat { Id = 35, Name = "golubsko-dobrzyński", Province = ProvinceProvider.Get(2), Sanitize = "golubsko_dobrzynski", Capital = "0" };
            yield return new Poviat { Id = 36, Name = "grudziądzki", Province = ProvinceProvider.Get(2), Sanitize = "grudziadzki", Capital = "286" };
            yield return new Poviat { Id = 37, Name = "inowrocławski", Province = ProvinceProvider.Get(2), Sanitize = "inowroclawski", Capital = "0" };
            yield return new Poviat { Id = 38, Name = "lipnowski", Province = ProvinceProvider.Get(2), Sanitize = "lipnowski", Capital = "0" };
            yield return new Poviat { Id = 39, Name = "mogileński", Province = ProvinceProvider.Get(2), Sanitize = "mogilenski", Capital = "0" };
            yield return new Poviat { Id = 40, Name = "nakielski", Province = ProvinceProvider.Get(2), Sanitize = "nakielski", Capital = "0" };
            yield return new Poviat { Id = 41, Name = "radziejowski", Province = ProvinceProvider.Get(2), Sanitize = "radziejowski", Capital = "0" };
            yield return new Poviat { Id = 42, Name = "rypiński", Province = ProvinceProvider.Get(2), Sanitize = "rypinski", Capital = "0" };
            yield return new Poviat { Id = 43, Name = "sępoleński", Province = ProvinceProvider.Get(2), Sanitize = "sepolenski", Capital = "0" };
            yield return new Poviat { Id = 44, Name = "świecki", Province = ProvinceProvider.Get(2), Sanitize = "swiecki", Capital = "0" };
            yield return new Poviat { Id = 45, Name = "toruński", Province = ProvinceProvider.Get(2), Sanitize = "torunski", Capital = "287" };
            yield return new Poviat { Id = 46, Name = "tucholski", Province = ProvinceProvider.Get(2), Sanitize = "tucholski", Capital = "0" };
            yield return new Poviat { Id = 47, Name = "wąbrzeski", Province = ProvinceProvider.Get(2), Sanitize = "wabrzeski", Capital = "0" };
            yield return new Poviat { Id = 48, Name = "włocławski", Province = ProvinceProvider.Get(2), Sanitize = "wloclawski", Capital = "288" };
            yield return new Poviat { Id = 49, Name = "żniński", Province = ProvinceProvider.Get(2), Sanitize = "zninski", Capital = "0" };
            yield return new Poviat { Id = 50, Name = "Bydgoszcz m.", Province = ProvinceProvider.Get(2), Sanitize = "bydgoszcz_miasto", Capital = "0" };
            yield return new Poviat { Id = 51, Name = "Grudziądz m.", Province = ProvinceProvider.Get(2), Sanitize = "grudziadz_miasto", Capital = "0" };
            yield return new Poviat { Id = 52, Name = "Toruń m.", Province = ProvinceProvider.Get(2), Sanitize = "torun_miasto", Capital = "0" };
            yield return new Poviat { Id = 53, Name = "Włocławek m.", Province = ProvinceProvider.Get(2), Sanitize = "wloclawek_miasto", Capital = "0" };
            yield return new Poviat { Id = 54, Name = "bialski", Province = ProvinceProvider.Get(3), Sanitize = "bialski", Capital = "484" };
            yield return new Poviat { Id = 55, Name = "biłgorajski", Province = ProvinceProvider.Get(3), Sanitize = "bilgorajski", Capital = "0" };
            yield return new Poviat { Id = 56, Name = "chełmski", Province = ProvinceProvider.Get(3), Sanitize = "chelmski", Capital = "485" };
            yield return new Poviat { Id = 57, Name = "hrubieszowski", Province = ProvinceProvider.Get(3), Sanitize = "hrubieszowski", Capital = "0" };
            yield return new Poviat { Id = 58, Name = "janowski", Province = ProvinceProvider.Get(3), Sanitize = "janowski", Capital = "0" };
            yield return new Poviat { Id = 59, Name = "krasnostawski", Province = ProvinceProvider.Get(3), Sanitize = "krasnostawski", Capital = "0" };
            yield return new Poviat { Id = 60, Name = "kraśnicki", Province = ProvinceProvider.Get(3), Sanitize = "krasnicki", Capital = "0" };
            yield return new Poviat { Id = 61, Name = "lubartowski", Province = ProvinceProvider.Get(3), Sanitize = "lubartowski", Capital = "0" };
            yield return new Poviat { Id = 62, Name = "lubelski", Province = ProvinceProvider.Get(3), Sanitize = "lubelski", Capital = "486" };
            yield return new Poviat { Id = 63, Name = "łęczyński", Province = ProvinceProvider.Get(3), Sanitize = "leczynski", Capital = "0" };
            yield return new Poviat { Id = 64, Name = "łukowski", Province = ProvinceProvider.Get(3), Sanitize = "lukowski", Capital = "0" };
            yield return new Poviat { Id = 65, Name = "opolski", Province = ProvinceProvider.Get(3), Sanitize = "opolski", Capital = "0" };
            yield return new Poviat { Id = 66, Name = "parczewski", Province = ProvinceProvider.Get(3), Sanitize = "parczewski", Capital = "0" };
            yield return new Poviat { Id = 67, Name = "puławski", Province = ProvinceProvider.Get(3), Sanitize = "pulawski", Capital = "0" };
            yield return new Poviat { Id = 68, Name = "radzyński", Province = ProvinceProvider.Get(3), Sanitize = "radzynski", Capital = "0" };
            yield return new Poviat { Id = 69, Name = "rycki", Province = ProvinceProvider.Get(3), Sanitize = "rycki", Capital = "0" };
            yield return new Poviat { Id = 70, Name = "świdnicki", Province = ProvinceProvider.Get(3), Sanitize = "swidnicki", Capital = "0" };
            yield return new Poviat { Id = 71, Name = "tomaszowski", Province = ProvinceProvider.Get(3), Sanitize = "tomaszowski", Capital = "0" };
            yield return new Poviat { Id = 72, Name = "włodawski", Province = ProvinceProvider.Get(3), Sanitize = "wlodawski", Capital = "0" };
            yield return new Poviat { Id = 73, Name = "zamojski", Province = ProvinceProvider.Get(3), Sanitize = "zamojski", Capital = "487" };
            yield return new Poviat { Id = 74, Name = "Biała Podlaska m.", Province = ProvinceProvider.Get(3), Sanitize = "biala_podlaska_miasto", Capital = "0" };
            yield return new Poviat { Id = 75, Name = "Chełm m.", Province = ProvinceProvider.Get(3), Sanitize = "chelm_miasto", Capital = "0" };
            yield return new Poviat { Id = 76, Name = "Lublin m.", Province = ProvinceProvider.Get(3), Sanitize = "lublin_miasto", Capital = "0" };
            yield return new Poviat { Id = 77, Name = "Zamość m.", Province = ProvinceProvider.Get(3), Sanitize = "zamosc_miasto", Capital = "0" };
            yield return new Poviat { Id = 78, Name = "gorzowski", Province = ProvinceProvider.Get(4), Sanitize = "gorzowski", Capital = "565" };
            yield return new Poviat { Id = 79, Name = "krośnieński", Province = ProvinceProvider.Get(4), Sanitize = "krosnienski", Capital = "0" };
            yield return new Poviat { Id = 80, Name = "międzyrzecki", Province = ProvinceProvider.Get(4), Sanitize = "miedzyrzecki", Capital = "0" };
            yield return new Poviat { Id = 81, Name = "nowosolski", Province = ProvinceProvider.Get(4), Sanitize = "nowosolski", Capital = "0" };
            yield return new Poviat { Id = 82, Name = "słubicki", Province = ProvinceProvider.Get(4), Sanitize = "slubicki", Capital = "0" };
            yield return new Poviat { Id = 83, Name = "strzelecko-drezdenecki", Province = ProvinceProvider.Get(4), Sanitize = "strzelecko_drezdenecki", Capital = "0" };
            yield return new Poviat { Id = 84, Name = "sulęciński", Province = ProvinceProvider.Get(4), Sanitize = "sulecinski", Capital = "0" };
            yield return new Poviat { Id = 85, Name = "świebodziński", Province = ProvinceProvider.Get(4), Sanitize = "swiebodzinski", Capital = "0" };
            yield return new Poviat { Id = 86, Name = "zielonogórski", Province = ProvinceProvider.Get(4), Sanitize = "zielonogorski", Capital = "566" };
            yield return new Poviat { Id = 87, Name = "żagański", Province = ProvinceProvider.Get(4), Sanitize = "zaganski", Capital = "0" };
            yield return new Poviat { Id = 88, Name = "żarski", Province = ProvinceProvider.Get(4), Sanitize = "zarski", Capital = "0" };
            yield return new Poviat { Id = 89, Name = "Gorzów Wielkopolski m.", Province = ProvinceProvider.Get(4), Sanitize = "gorzow_wielkopolski_miasto", Capital = "0" };
            yield return new Poviat { Id = 90, Name = "Zielona Góra m.", Province = ProvinceProvider.Get(4), Sanitize = "zielona_gora_miasto", Capital = "0" };
            yield return new Poviat { Id = 91, Name = "bełchatowski", Province = ProvinceProvider.Get(5), Sanitize = "belchatowski", Capital = "0" };
            yield return new Poviat { Id = 92, Name = "kutnowski", Province = ProvinceProvider.Get(5), Sanitize = "kutnowski", Capital = "0" };
            yield return new Poviat { Id = 93, Name = "łaski", Province = ProvinceProvider.Get(5), Sanitize = "laski", Capital = "0" };
            yield return new Poviat { Id = 94, Name = "łęczycki", Province = ProvinceProvider.Get(5), Sanitize = "leczycki", Capital = "0" };
            yield return new Poviat { Id = 95, Name = "łowicki", Province = ProvinceProvider.Get(5), Sanitize = "lowicki", Capital = "0" };
            yield return new Poviat { Id = 96, Name = "łódzki wschodni", Province = ProvinceProvider.Get(5), Sanitize = "lodzki_wschodni", Capital = "0" };
            yield return new Poviat { Id = 97, Name = "opoczyński", Province = ProvinceProvider.Get(5), Sanitize = "opoczynski", Capital = "0" };
            yield return new Poviat { Id = 98, Name = "pabianicki", Province = ProvinceProvider.Get(5), Sanitize = "pabianicki", Capital = "0" };
            yield return new Poviat { Id = 99, Name = "pajęczański", Province = ProvinceProvider.Get(5), Sanitize = "pajeczanski", Capital = "0" };
            yield return new Poviat { Id = 100, Name = "piotrkowski", Province = ProvinceProvider.Get(5), Sanitize = "piotrkowski", Capital = "727" };
            yield return new Poviat { Id = 101, Name = "poddębicki", Province = ProvinceProvider.Get(5), Sanitize = "poddebicki", Capital = "0" };
            yield return new Poviat { Id = 102, Name = "radomszczański", Province = ProvinceProvider.Get(5), Sanitize = "radomszczanski", Capital = "0" };
            yield return new Poviat { Id = 103, Name = "rawski", Province = ProvinceProvider.Get(5), Sanitize = "rawski", Capital = "0" };
            yield return new Poviat { Id = 104, Name = "sieradzki", Province = ProvinceProvider.Get(5), Sanitize = "sieradzki", Capital = "0" };
            yield return new Poviat { Id = 105, Name = "skierniewicki", Province = ProvinceProvider.Get(5), Sanitize = "skierniewicki", Capital = "728" };
            yield return new Poviat { Id = 106, Name = "tomaszowski", Province = ProvinceProvider.Get(5), Sanitize = "tomaszowski", Capital = "0" };
            yield return new Poviat { Id = 107, Name = "wieluński", Province = ProvinceProvider.Get(5), Sanitize = "wielunski", Capital = "0" };
            yield return new Poviat { Id = 108, Name = "wieruszowski", Province = ProvinceProvider.Get(5), Sanitize = "wieruszowski", Capital = "0" };
            yield return new Poviat { Id = 109, Name = "zduńskowolski", Province = ProvinceProvider.Get(5), Sanitize = "zdunskowolski", Capital = "0" };
            yield return new Poviat { Id = 110, Name = "zgierski", Province = ProvinceProvider.Get(5), Sanitize = "zgierski", Capital = "0" };
            yield return new Poviat { Id = 111, Name = "Łódź m.", Province = ProvinceProvider.Get(5), Sanitize = "lodz_miasto", Capital = "0" };
            yield return new Poviat { Id = 112, Name = "Piotrków Trybunalski m.", Province = ProvinceProvider.Get(5), Sanitize = "piotrkow_trybunalski_miasto", Capital = "0" };
            yield return new Poviat { Id = 113, Name = "Skierniewice m.", Province = ProvinceProvider.Get(5), Sanitize = "skierniewice_miasto", Capital = "0" };
            yield return new Poviat { Id = 114, Name = "bocheński", Province = ProvinceProvider.Get(6), Sanitize = "bochenski", Capital = "0" };
            yield return new Poviat { Id = 115, Name = "brzeski", Province = ProvinceProvider.Get(6), Sanitize = "brzeski", Capital = "0" };
            yield return new Poviat { Id = 116, Name = "chrzanowski", Province = ProvinceProvider.Get(6), Sanitize = "chrzanowski", Capital = "0" };
            yield return new Poviat { Id = 117, Name = "dąbrowski", Province = ProvinceProvider.Get(6), Sanitize = "dabrowski", Capital = "0" };
            yield return new Poviat { Id = 118, Name = "gorlicki", Province = ProvinceProvider.Get(6), Sanitize = "gorlicki", Capital = "0" };
            yield return new Poviat { Id = 119, Name = "krakowski", Province = ProvinceProvider.Get(6), Sanitize = "krakowski", Capital = "901" };
            yield return new Poviat { Id = 120, Name = "limanowski", Province = ProvinceProvider.Get(6), Sanitize = "limanowski", Capital = "0" };
            yield return new Poviat { Id = 121, Name = "miechowski", Province = ProvinceProvider.Get(6), Sanitize = "miechowski", Capital = "0" };
            yield return new Poviat { Id = 122, Name = "myślenicki", Province = ProvinceProvider.Get(6), Sanitize = "myslenicki", Capital = "0" };
            yield return new Poviat { Id = 123, Name = "nowosądecki", Province = ProvinceProvider.Get(6), Sanitize = "nowosadecki", Capital = "902" };
            yield return new Poviat { Id = 124, Name = "nowotarski", Province = ProvinceProvider.Get(6), Sanitize = "nowotarski", Capital = "0" };
            yield return new Poviat { Id = 125, Name = "olkuski", Province = ProvinceProvider.Get(6), Sanitize = "olkuski", Capital = "0" };
            yield return new Poviat { Id = 126, Name = "oświęcimski", Province = ProvinceProvider.Get(6), Sanitize = "oswiecimski", Capital = "0" };
            yield return new Poviat { Id = 127, Name = "proszowicki", Province = ProvinceProvider.Get(6), Sanitize = "proszowicki", Capital = "0" };
            yield return new Poviat { Id = 128, Name = "suski", Province = ProvinceProvider.Get(6), Sanitize = "suski", Capital = "0" };
            yield return new Poviat { Id = 129, Name = "tarnowski", Province = ProvinceProvider.Get(6), Sanitize = "tarnowski", Capital = "903" };
            yield return new Poviat { Id = 130, Name = "tatrzański", Province = ProvinceProvider.Get(6), Sanitize = "tatrzanski", Capital = "0" };
            yield return new Poviat { Id = 131, Name = "wadowicki", Province = ProvinceProvider.Get(6), Sanitize = "wadowicki", Capital = "0" };
            yield return new Poviat { Id = 132, Name = "wielicki", Province = ProvinceProvider.Get(6), Sanitize = "wielicki", Capital = "0" };
            yield return new Poviat { Id = 133, Name = "Kraków m.", Province = ProvinceProvider.Get(6), Sanitize = "krakow_miasto", Capital = "0" };
            yield return new Poviat { Id = 134, Name = "Nowy Sącz m.", Province = ProvinceProvider.Get(6), Sanitize = "nowy_sacz_miasto", Capital = "0" };
            yield return new Poviat { Id = 135, Name = "Tarnów m.", Province = ProvinceProvider.Get(6), Sanitize = "tarnow_miasto", Capital = "0" };
            yield return new Poviat { Id = 136, Name = "białobrzeski", Province = ProvinceProvider.Get(7), Sanitize = "bialobrzeski", Capital = "0" };
            yield return new Poviat { Id = 137, Name = "ciechanowski", Province = ProvinceProvider.Get(7), Sanitize = "ciechanowski", Capital = "0" };
            yield return new Poviat { Id = 138, Name = "garwoliński", Province = ProvinceProvider.Get(7), Sanitize = "garwolinski", Capital = "0" };
            yield return new Poviat { Id = 139, Name = "gostyniński", Province = ProvinceProvider.Get(7), Sanitize = "gostyninski", Capital = "0" };
            yield return new Poviat { Id = 140, Name = "grodziski", Province = ProvinceProvider.Get(7), Sanitize = "grodziski", Capital = "0" };
            yield return new Poviat { Id = 141, Name = "grójecki", Province = ProvinceProvider.Get(7), Sanitize = "grojecki", Capital = "0" };
            yield return new Poviat { Id = 142, Name = "kozienicki", Province = ProvinceProvider.Get(7), Sanitize = "kozienicki", Capital = "0" };
            yield return new Poviat { Id = 143, Name = "legionowski", Province = ProvinceProvider.Get(7), Sanitize = "legionowski", Capital = "0" };
            yield return new Poviat { Id = 144, Name = "lipski", Province = ProvinceProvider.Get(7), Sanitize = "lipski", Capital = "0" };
            yield return new Poviat { Id = 145, Name = "łosicki", Province = ProvinceProvider.Get(7), Sanitize = "losicki", Capital = "0" };
            yield return new Poviat { Id = 146, Name = "makowski", Province = ProvinceProvider.Get(7), Sanitize = "makowski", Capital = "0" };
            yield return new Poviat { Id = 147, Name = "miński", Province = ProvinceProvider.Get(7), Sanitize = "minski", Capital = "0" };
            yield return new Poviat { Id = 148, Name = "mławski", Province = ProvinceProvider.Get(7), Sanitize = "mlawski", Capital = "0" };
            yield return new Poviat { Id = 149, Name = "nowodworski", Province = ProvinceProvider.Get(7), Sanitize = "nowodworski", Capital = "0" };
            yield return new Poviat { Id = 150, Name = "ostrołęcki", Province = ProvinceProvider.Get(7), Sanitize = "ostrolecki", Capital = "1201" };
            yield return new Poviat { Id = 151, Name = "ostrowski", Province = ProvinceProvider.Get(7), Sanitize = "ostrowski", Capital = "0" };
            yield return new Poviat { Id = 152, Name = "otwocki", Province = ProvinceProvider.Get(7), Sanitize = "otwocki", Capital = "0" };
            yield return new Poviat { Id = 153, Name = "piaseczyński", Province = ProvinceProvider.Get(7), Sanitize = "piaseczynski", Capital = "0" };
            yield return new Poviat { Id = 154, Name = "płocki", Province = ProvinceProvider.Get(7), Sanitize = "plocki", Capital = "1202" };
            yield return new Poviat { Id = 155, Name = "płoński", Province = ProvinceProvider.Get(7), Sanitize = "plonski", Capital = "0" };
            yield return new Poviat { Id = 156, Name = "pruszkowski", Province = ProvinceProvider.Get(7), Sanitize = "pruszkowski", Capital = "0" };
            yield return new Poviat { Id = 157, Name = "przasnyski", Province = ProvinceProvider.Get(7), Sanitize = "przasnyski", Capital = "0" };
            yield return new Poviat { Id = 158, Name = "przysuski", Province = ProvinceProvider.Get(7), Sanitize = "przysuski", Capital = "0" };
            yield return new Poviat { Id = 159, Name = "pułtuski", Province = ProvinceProvider.Get(7), Sanitize = "pultuski", Capital = "0" };
            yield return new Poviat { Id = 160, Name = "radomski", Province = ProvinceProvider.Get(7), Sanitize = "radomski", Capital = "1203" };
            yield return new Poviat { Id = 161, Name = "siedlecki", Province = ProvinceProvider.Get(7), Sanitize = "siedlecki", Capital = "1204" };
            yield return new Poviat { Id = 162, Name = "sierpecki", Province = ProvinceProvider.Get(7), Sanitize = "sierpecki", Capital = "0" };
            yield return new Poviat { Id = 163, Name = "sochaczewski", Province = ProvinceProvider.Get(7), Sanitize = "sochaczewski", Capital = "0" };
            yield return new Poviat { Id = 164, Name = "sokołowski", Province = ProvinceProvider.Get(7), Sanitize = "sokolowski", Capital = "0" };
            yield return new Poviat { Id = 165, Name = "szydłowiecki", Province = ProvinceProvider.Get(7), Sanitize = "szydlowiecki", Capital = "0" };
            yield return new Poviat { Id = 166, Name = "Warszawa m.", Province = ProvinceProvider.Get(7), Sanitize = "warszawa_miasto", Capital = "0" };
            yield return new Poviat { Id = 167, Name = "warszawski zachodni", Province = ProvinceProvider.Get(7), Sanitize = "warszawski_zachodni", Capital = "0" };
            yield return new Poviat { Id = 168, Name = "węgrowski", Province = ProvinceProvider.Get(7), Sanitize = "wegrowski", Capital = "0" };
            yield return new Poviat { Id = 169, Name = "wołomiński", Province = ProvinceProvider.Get(7), Sanitize = "wolominski", Capital = "0" };
            yield return new Poviat { Id = 170, Name = "wyszkowski", Province = ProvinceProvider.Get(7), Sanitize = "wyszkowski", Capital = "0" };
            yield return new Poviat { Id = 171, Name = "zwoleński", Province = ProvinceProvider.Get(7), Sanitize = "zwolenski", Capital = "0" };
            yield return new Poviat { Id = 172, Name = "żuromiński", Province = ProvinceProvider.Get(7), Sanitize = "zurominski", Capital = "0" };
            yield return new Poviat { Id = 173, Name = "żyrardowski", Province = ProvinceProvider.Get(7), Sanitize = "zyrardowski", Capital = "0" };
            yield return new Poviat { Id = 174, Name = "Ostrołęka m.", Province = ProvinceProvider.Get(7), Sanitize = "ostroleka_miasto", Capital = "0" };
            yield return new Poviat { Id = 175, Name = "Płock m.", Province = ProvinceProvider.Get(7), Sanitize = "plock_miasto", Capital = "0" };
            yield return new Poviat { Id = 176, Name = "Radom m.", Province = ProvinceProvider.Get(7), Sanitize = "radom_miasto", Capital = "0" };
            yield return new Poviat { Id = 177, Name = "Siedlce m.", Province = ProvinceProvider.Get(7), Sanitize = "siedlce_miasto", Capital = "0" };
            yield return new Poviat { Id = 178, Name = "brzeski", Province = ProvinceProvider.Get(8), Sanitize = "brzeski", Capital = "0" };
            yield return new Poviat { Id = 179, Name = "głubczycki", Province = ProvinceProvider.Get(8), Sanitize = "glubczycki", Capital = "0" };
            yield return new Poviat { Id = 180, Name = "kędzierzyńsko-kozielski", Province = ProvinceProvider.Get(8), Sanitize = "kedzierzynsko_kozielski", Capital = "0" };
            yield return new Poviat { Id = 181, Name = "kluczborski", Province = ProvinceProvider.Get(8), Sanitize = "kluczborski", Capital = "0" };
            yield return new Poviat { Id = 182, Name = "krapkowicki", Province = ProvinceProvider.Get(8), Sanitize = "krapkowicki", Capital = "0" };
            yield return new Poviat { Id = 183, Name = "namysłowski", Province = ProvinceProvider.Get(8), Sanitize = "namyslowski", Capital = "0" };
            yield return new Poviat { Id = 184, Name = "nyski", Province = ProvinceProvider.Get(8), Sanitize = "nyski", Capital = "0" };
            yield return new Poviat { Id = 185, Name = "oleski", Province = ProvinceProvider.Get(8), Sanitize = "oleski", Capital = "0" };
            yield return new Poviat { Id = 186, Name = "opolski", Province = ProvinceProvider.Get(8), Sanitize = "opolski", Capital = "1274" };
            yield return new Poviat { Id = 187, Name = "prudnicki", Province = ProvinceProvider.Get(8), Sanitize = "prudnicki", Capital = "0" };
            yield return new Poviat { Id = 188, Name = "strzelecki", Province = ProvinceProvider.Get(8), Sanitize = "strzelecki", Capital = "0" };
            yield return new Poviat { Id = 189, Name = "Opole m.", Province = ProvinceProvider.Get(8), Sanitize = "opole_miasto", Capital = "0" };
            yield return new Poviat { Id = 190, Name = "bieszczadzki", Province = ProvinceProvider.Get(9), Sanitize = "bieszczadzki", Capital = "0" };
            yield return new Poviat { Id = 191, Name = "brzozowski", Province = ProvinceProvider.Get(9), Sanitize = "brzozowski", Capital = "0" };
            yield return new Poviat { Id = 192, Name = "dębicki", Province = ProvinceProvider.Get(9), Sanitize = "debicki", Capital = "0" };
            yield return new Poviat { Id = 193, Name = "jarosławski", Province = ProvinceProvider.Get(9), Sanitize = "jaroslawski", Capital = "0" };
            yield return new Poviat { Id = 194, Name = "jasielski", Province = ProvinceProvider.Get(9), Sanitize = "jasielski", Capital = "0" };
            yield return new Poviat { Id = 195, Name = "kolbuszowski", Province = ProvinceProvider.Get(9), Sanitize = "kolbuszowski", Capital = "0" };
            yield return new Poviat { Id = 196, Name = "krośnieński", Province = ProvinceProvider.Get(9), Sanitize = "krosnienski", Capital = "1420" };
            yield return new Poviat { Id = 197, Name = "leżajski", Province = ProvinceProvider.Get(9), Sanitize = "lezajski", Capital = "0" };
            yield return new Poviat { Id = 198, Name = "lubaczowski", Province = ProvinceProvider.Get(9), Sanitize = "lubaczowski", Capital = "0" };
            yield return new Poviat { Id = 199, Name = "łańcucki", Province = ProvinceProvider.Get(9), Sanitize = "lancucki", Capital = "0" };
            yield return new Poviat { Id = 200, Name = "mielecki", Province = ProvinceProvider.Get(9), Sanitize = "mielecki", Capital = "0" };
            yield return new Poviat { Id = 201, Name = "niżański", Province = ProvinceProvider.Get(9), Sanitize = "nizanski", Capital = "0" };
            yield return new Poviat { Id = 202, Name = "przemyski", Province = ProvinceProvider.Get(9), Sanitize = "przemyski", Capital = "1421" };
            yield return new Poviat { Id = 203, Name = "przeworski", Province = ProvinceProvider.Get(9), Sanitize = "przeworski", Capital = "0" };
            yield return new Poviat { Id = 204, Name = "ropczycko-sędziszowski", Province = ProvinceProvider.Get(9), Sanitize = "ropczycko_sedziszowski", Capital = "0" };
            yield return new Poviat { Id = 205, Name = "rzeszowski", Province = ProvinceProvider.Get(9), Sanitize = "rzeszowski", Capital = "1422" };
            yield return new Poviat { Id = 206, Name = "sanocki", Province = ProvinceProvider.Get(9), Sanitize = "sanocki", Capital = "0" };
            yield return new Poviat { Id = 207, Name = "stalowowolski", Province = ProvinceProvider.Get(9), Sanitize = "stalowowolski", Capital = "0" };
            yield return new Poviat { Id = 208, Name = "strzyżowski", Province = ProvinceProvider.Get(9), Sanitize = "strzyzowski", Capital = "0" };
            yield return new Poviat { Id = 209, Name = "tarnobrzeski", Province = ProvinceProvider.Get(9), Sanitize = "tarnobrzeski", Capital = "1423" };
            yield return new Poviat { Id = 210, Name = "Krosno m.", Province = ProvinceProvider.Get(9), Sanitize = "krosno_miasto", Capital = "0" };
            yield return new Poviat { Id = 211, Name = "Przemyśl m.", Province = ProvinceProvider.Get(9), Sanitize = "przemysl_miasto", Capital = "0" };
            yield return new Poviat { Id = 212, Name = "Rzeszów m.", Province = ProvinceProvider.Get(9), Sanitize = "rzeszow_miasto", Capital = "0" };
            yield return new Poviat { Id = 213, Name = "Tarnobrzeg m.", Province = ProvinceProvider.Get(9), Sanitize = "tarnobrzeg_miasto", Capital = "0" };
            yield return new Poviat { Id = 214, Name = "augustowski", Province = ProvinceProvider.Get(10), Sanitize = "augustowski", Capital = "0" };
            yield return new Poviat { Id = 215, Name = "białostocki", Province = ProvinceProvider.Get(10), Sanitize = "bialostocki", Capital = "1529" };
            yield return new Poviat { Id = 216, Name = "bielski", Province = ProvinceProvider.Get(10), Sanitize = "bielski", Capital = "0" };
            yield return new Poviat { Id = 217, Name = "grajewski", Province = ProvinceProvider.Get(10), Sanitize = "grajewski", Capital = "0" };
            yield return new Poviat { Id = 218, Name = "hajnowski", Province = ProvinceProvider.Get(10), Sanitize = "hajnowski", Capital = "0" };
            yield return new Poviat { Id = 219, Name = "kolneński", Province = ProvinceProvider.Get(10), Sanitize = "kolnenski", Capital = "0" };
            yield return new Poviat { Id = 220, Name = "łomżyński", Province = ProvinceProvider.Get(10), Sanitize = "lomzynski", Capital = "1530" };
            yield return new Poviat { Id = 221, Name = "moniecki", Province = ProvinceProvider.Get(10), Sanitize = "moniecki", Capital = "0" };
            yield return new Poviat { Id = 222, Name = "sejneński", Province = ProvinceProvider.Get(10), Sanitize = "sejnenski", Capital = "0" };
            yield return new Poviat { Id = 223, Name = "siemiatycki", Province = ProvinceProvider.Get(10), Sanitize = "siemiatycki", Capital = "0" };
            yield return new Poviat { Id = 224, Name = "sokólski", Province = ProvinceProvider.Get(10), Sanitize = "sokolski", Capital = "0" };
            yield return new Poviat { Id = 225, Name = "suwalski", Province = ProvinceProvider.Get(10), Sanitize = "suwalski", Capital = "1531" };
            yield return new Poviat { Id = 226, Name = "wysokomazowiecki", Province = ProvinceProvider.Get(10), Sanitize = "wysokomazowiecki", Capital = "0" };
            yield return new Poviat { Id = 227, Name = "zambrowski", Province = ProvinceProvider.Get(10), Sanitize = "zambrowski", Capital = "0" };
            yield return new Poviat { Id = 228, Name = "Białystok m.", Province = ProvinceProvider.Get(10), Sanitize = "bialystok_miasto", Capital = "0" };
            yield return new Poviat { Id = 229, Name = "Łomża m.", Province = ProvinceProvider.Get(10), Sanitize = "lomza_miasto", Capital = "0" };
            yield return new Poviat { Id = 230, Name = "Suwałki m.", Province = ProvinceProvider.Get(10), Sanitize = "suwalki_miasto", Capital = "0" };
            yield return new Poviat { Id = 231, Name = "bytowski", Province = ProvinceProvider.Get(11), Sanitize = "bytowski", Capital = "0" };
            yield return new Poviat { Id = 232, Name = "chojnicki", Province = ProvinceProvider.Get(11), Sanitize = "chojnicki", Capital = "0" };
            yield return new Poviat { Id = 233, Name = "człuchowski", Province = ProvinceProvider.Get(11), Sanitize = "czluchowski", Capital = "0" };
            yield return new Poviat { Id = 234, Name = "gdański", Province = ProvinceProvider.Get(11), Sanitize = "gdanski", Capital = "0" };
            yield return new Poviat { Id = 235, Name = "kartuski", Province = ProvinceProvider.Get(11), Sanitize = "kartuski", Capital = "0" };
            yield return new Poviat { Id = 236, Name = "kościerski", Province = ProvinceProvider.Get(11), Sanitize = "koscierski", Capital = "0" };
            yield return new Poviat { Id = 237, Name = "kwidzyński", Province = ProvinceProvider.Get(11), Sanitize = "kwidzynski", Capital = "0" };
            yield return new Poviat { Id = 238, Name = "lęborski", Province = ProvinceProvider.Get(11), Sanitize = "leborski", Capital = "0" };
            yield return new Poviat { Id = 239, Name = "malborski", Province = ProvinceProvider.Get(11), Sanitize = "malborski", Capital = "0" };
            yield return new Poviat { Id = 240, Name = "nowodworski", Province = ProvinceProvider.Get(11), Sanitize = "nowodworski", Capital = "0" };
            yield return new Poviat { Id = 241, Name = "pucki", Province = ProvinceProvider.Get(11), Sanitize = "pucki", Capital = "0" };
            yield return new Poviat { Id = 242, Name = "słupski", Province = ProvinceProvider.Get(11), Sanitize = "slupski", Capital = "1641" };
            yield return new Poviat { Id = 243, Name = "starogardzki", Province = ProvinceProvider.Get(11), Sanitize = "starogardzki", Capital = "0" };
            yield return new Poviat { Id = 244, Name = "tczewski", Province = ProvinceProvider.Get(11), Sanitize = "tczewski", Capital = "0" };
            yield return new Poviat { Id = 245, Name = "wejherowski", Province = ProvinceProvider.Get(11), Sanitize = "wejherowski", Capital = "0" };
            yield return new Poviat { Id = 246, Name = "Gdańsk m.", Province = ProvinceProvider.Get(11), Sanitize = "gdansk_miasto", Capital = "0" };
            yield return new Poviat { Id = 247, Name = "Gdynia m.", Province = ProvinceProvider.Get(11), Sanitize = "gdynia_miasto", Capital = "0" };
            yield return new Poviat { Id = 248, Name = "Słupsk m.", Province = ProvinceProvider.Get(11), Sanitize = "slupsk_miasto", Capital = "0" };
            yield return new Poviat { Id = 249, Name = "Sopot m.", Province = ProvinceProvider.Get(11), Sanitize = "sopot_miasto", Capital = "0" };
            yield return new Poviat { Id = 250, Name = "będziński", Province = ProvinceProvider.Get(12), Sanitize = "bedzinski", Capital = "0" };
            yield return new Poviat { Id = 251, Name = "bielski", Province = ProvinceProvider.Get(12), Sanitize = "bielski", Capital = "1790" };
            yield return new Poviat { Id = 252, Name = "cieszyński", Province = ProvinceProvider.Get(12), Sanitize = "cieszynski", Capital = "0" };
            yield return new Poviat { Id = 253, Name = "częstochowski", Province = ProvinceProvider.Get(12), Sanitize = "czestochowski", Capital = "1793" };
            yield return new Poviat { Id = 254, Name = "gliwicki", Province = ProvinceProvider.Get(12), Sanitize = "gliwicki", Capital = "1795" };
            yield return new Poviat { Id = 255, Name = "kłobucki", Province = ProvinceProvider.Get(12), Sanitize = "klobucki", Capital = "0" };
            yield return new Poviat { Id = 256, Name = "lubliniecki", Province = ProvinceProvider.Get(12), Sanitize = "lubliniecki", Capital = "0" };
            yield return new Poviat { Id = 257, Name = "mikołowski", Province = ProvinceProvider.Get(12), Sanitize = "mikolowski", Capital = "0" };
            yield return new Poviat { Id = 258, Name = "myszkowski", Province = ProvinceProvider.Get(12), Sanitize = "myszkowski", Capital = "0" };
            yield return new Poviat { Id = 259, Name = "pszczyński", Province = ProvinceProvider.Get(12), Sanitize = "pszczynski", Capital = "0" };
            yield return new Poviat { Id = 260, Name = "raciborski", Province = ProvinceProvider.Get(12), Sanitize = "raciborski", Capital = "0" };
            yield return new Poviat { Id = 261, Name = "rybnicki", Province = ProvinceProvider.Get(12), Sanitize = "rybnicki", Capital = "1802" };
            yield return new Poviat { Id = 262, Name = "tarnogórski", Province = ProvinceProvider.Get(12), Sanitize = "tarnogorski", Capital = "0" };
            yield return new Poviat { Id = 263, Name = "bieruńsko-lędziński", Province = ProvinceProvider.Get(12), Sanitize = "bierunsko_ledzinski", Capital = "0" };
            yield return new Poviat { Id = 264, Name = "wodzisławski", Province = ProvinceProvider.Get(12), Sanitize = "wodzislawski", Capital = "0" };
            yield return new Poviat { Id = 265, Name = "zawierciański", Province = ProvinceProvider.Get(12), Sanitize = "zawiercianski", Capital = "0" };
            yield return new Poviat { Id = 266, Name = "żywiecki", Province = ProvinceProvider.Get(12), Sanitize = "zywiecki", Capital = "0" };
            yield return new Poviat { Id = 267, Name = "Bielsko-Biała m.", Province = ProvinceProvider.Get(12), Sanitize = "bielsko_biala_miasto", Capital = "0" };
            yield return new Poviat { Id = 268, Name = "Bytom m.", Province = ProvinceProvider.Get(12), Sanitize = "bytom_miasto", Capital = "0" };
            yield return new Poviat { Id = 269, Name = "Chorzów m.", Province = ProvinceProvider.Get(12), Sanitize = "chorzow_miasto", Capital = "0" };
            yield return new Poviat { Id = 270, Name = "Częstochowa m.", Province = ProvinceProvider.Get(12), Sanitize = "czestochowa_miasto", Capital = "0" };
            yield return new Poviat { Id = 271, Name = "Dąbrowa Górnicza m.", Province = ProvinceProvider.Get(12), Sanitize = "dabrowa_gornicza_miasto", Capital = "0" };
            yield return new Poviat { Id = 272, Name = "Gliwice m.", Province = ProvinceProvider.Get(12), Sanitize = "gliwice_miasto", Capital = "0" };
            yield return new Poviat { Id = 273, Name = "Jastrzębie-Zdrój m.", Province = ProvinceProvider.Get(12), Sanitize = "jastrzebie_zdroj_miasto", Capital = "0" };
            yield return new Poviat { Id = 274, Name = "Jaworzno m.", Province = ProvinceProvider.Get(12), Sanitize = "jaworzno_miasto", Capital = "0" };
            yield return new Poviat { Id = 275, Name = "Katowice m.", Province = ProvinceProvider.Get(12), Sanitize = "katowice_miasto", Capital = "0" };
            yield return new Poviat { Id = 276, Name = "Mysłowice m.", Province = ProvinceProvider.Get(12), Sanitize = "myslowice_miasto", Capital = "0" };
            yield return new Poviat { Id = 277, Name = "Piekary Śląskie m.", Province = ProvinceProvider.Get(12), Sanitize = "piekary_slaskie_miasto", Capital = "0" };
            yield return new Poviat { Id = 278, Name = "Ruda Śląska m.", Province = ProvinceProvider.Get(12), Sanitize = "ruda_slaska_miasto", Capital = "0" };
            yield return new Poviat { Id = 279, Name = "Rybnik m.", Province = ProvinceProvider.Get(12), Sanitize = "rybnik_miasto", Capital = "0" };
            yield return new Poviat { Id = 280, Name = "Siemianowice Śląskie m.", Province = ProvinceProvider.Get(12), Sanitize = "siemianowice_slaskie_miasto", Capital = "0" };
            yield return new Poviat { Id = 281, Name = "Sosnowiec m.", Province = ProvinceProvider.Get(12), Sanitize = "sosnowiec_miasto", Capital = "0" };
            yield return new Poviat { Id = 282, Name = "Świętochłowice m.", Province = ProvinceProvider.Get(12), Sanitize = "swietochlowice_miasto", Capital = "0" };
            yield return new Poviat { Id = 283, Name = "Tychy m.", Province = ProvinceProvider.Get(12), Sanitize = "tychy_miasto", Capital = "0" };
            yield return new Poviat { Id = 284, Name = "Zabrze m.", Province = ProvinceProvider.Get(12), Sanitize = "zabrze_miasto", Capital = "0" };
            yield return new Poviat { Id = 285, Name = "Żory m.", Province = ProvinceProvider.Get(12), Sanitize = "zory_miasto", Capital = "0" };
            yield return new Poviat { Id = 286, Name = "buski", Province = ProvinceProvider.Get(13), Sanitize = "buski", Capital = "0" };
            yield return new Poviat { Id = 287, Name = "jędrzejowski", Province = ProvinceProvider.Get(13), Sanitize = "jedrzejowski", Capital = "0" };
            yield return new Poviat { Id = 288, Name = "kazimierski", Province = ProvinceProvider.Get(13), Sanitize = "kazimierski", Capital = "0" };
            yield return new Poviat { Id = 289, Name = "kielecki", Province = ProvinceProvider.Get(13), Sanitize = "kielecki", Capital = "1910" };
            yield return new Poviat { Id = 290, Name = "konecki", Province = ProvinceProvider.Get(13), Sanitize = "konecki", Capital = "0" };
            yield return new Poviat { Id = 291, Name = "opatowski", Province = ProvinceProvider.Get(13), Sanitize = "opatowski", Capital = "0" };
            yield return new Poviat { Id = 292, Name = "ostrowiecki", Province = ProvinceProvider.Get(13), Sanitize = "ostrowiecki", Capital = "0" };
            yield return new Poviat { Id = 293, Name = "pińczowski", Province = ProvinceProvider.Get(13), Sanitize = "pinczowski", Capital = "0" };
            yield return new Poviat { Id = 294, Name = "sandomierski", Province = ProvinceProvider.Get(13), Sanitize = "sandomierski", Capital = "0" };
            yield return new Poviat { Id = 295, Name = "skarżyski", Province = ProvinceProvider.Get(13), Sanitize = "skarzyski", Capital = "0" };
            yield return new Poviat { Id = 296, Name = "starachowicki", Province = ProvinceProvider.Get(13), Sanitize = "starachowicki", Capital = "0" };
            yield return new Poviat { Id = 297, Name = "staszowski", Province = ProvinceProvider.Get(13), Sanitize = "staszowski", Capital = "0" };
            yield return new Poviat { Id = 298, Name = "włoszczowski", Province = ProvinceProvider.Get(13), Sanitize = "wloszczowski", Capital = "0" };
            yield return new Poviat { Id = 299, Name = "Kielce m.", Province = ProvinceProvider.Get(13), Sanitize = "kielce_miasto", Capital = "0" };
            yield return new Poviat { Id = 300, Name = "bartoszycki", Province = ProvinceProvider.Get(14), Sanitize = "bartoszycki", Capital = "0" };
            yield return new Poviat { Id = 301, Name = "braniewski", Province = ProvinceProvider.Get(14), Sanitize = "braniewski", Capital = "0" };
            yield return new Poviat { Id = 302, Name = "działdowski", Province = ProvinceProvider.Get(14), Sanitize = "dzialdowski", Capital = "0" };
            yield return new Poviat { Id = 303, Name = "elbląski", Province = ProvinceProvider.Get(14), Sanitize = "elblaski", Capital = "2011" };
            yield return new Poviat { Id = 304, Name = "ełcki", Province = ProvinceProvider.Get(14), Sanitize = "elcki", Capital = "0" };
            yield return new Poviat { Id = 305, Name = "giżycki", Province = ProvinceProvider.Get(14), Sanitize = "gizycki", Capital = "0" };
            yield return new Poviat { Id = 306, Name = "iławski", Province = ProvinceProvider.Get(14), Sanitize = "ilawski", Capital = "0" };
            yield return new Poviat { Id = 307, Name = "kętrzyński", Province = ProvinceProvider.Get(14), Sanitize = "ketrzynski", Capital = "0" };
            yield return new Poviat { Id = 308, Name = "lidzbarski", Province = ProvinceProvider.Get(14), Sanitize = "lidzbarski", Capital = "0" };
            yield return new Poviat { Id = 309, Name = "mrągowski", Province = ProvinceProvider.Get(14), Sanitize = "mragowski", Capital = "0" };
            yield return new Poviat { Id = 310, Name = "nidzicki", Province = ProvinceProvider.Get(14), Sanitize = "nidzicki", Capital = "0" };
            yield return new Poviat { Id = 311, Name = "nowomiejski", Province = ProvinceProvider.Get(14), Sanitize = "nowomiejski", Capital = "0" };
            yield return new Poviat { Id = 312, Name = "olecki", Province = ProvinceProvider.Get(14), Sanitize = "olecki", Capital = "0" };
            yield return new Poviat { Id = 313, Name = "olsztyński", Province = ProvinceProvider.Get(14), Sanitize = "olsztynski", Capital = "2012" };
            yield return new Poviat { Id = 314, Name = "ostródzki", Province = ProvinceProvider.Get(14), Sanitize = "ostrodzki", Capital = "0" };
            yield return new Poviat { Id = 315, Name = "piski", Province = ProvinceProvider.Get(14), Sanitize = "piski", Capital = "0" };
            yield return new Poviat { Id = 316, Name = "szczycieński", Province = ProvinceProvider.Get(14), Sanitize = "szczycienski", Capital = "0" };
            yield return new Poviat { Id = 317, Name = "Elbląg m.", Province = ProvinceProvider.Get(14), Sanitize = "elblag_miasto", Capital = "0" };
            yield return new Poviat { Id = 318, Name = "Olsztyn m.", Province = ProvinceProvider.Get(14), Sanitize = "olsztyn_miasto", Capital = "0" };
            yield return new Poviat { Id = 319, Name = "chodzieski", Province = ProvinceProvider.Get(15), Sanitize = "chodzieski", Capital = "0" };
            yield return new Poviat { Id = 320, Name = "czarnkowsko-trzcianecki", Province = ProvinceProvider.Get(15), Sanitize = "czarnkowsko_trzcianecki", Capital = "0" };
            yield return new Poviat { Id = 321, Name = "gnieźnieński", Province = ProvinceProvider.Get(15), Sanitize = "gnieznienski", Capital = "0" };
            yield return new Poviat { Id = 322, Name = "gostyński", Province = ProvinceProvider.Get(15), Sanitize = "gostynski", Capital = "0" };
            yield return new Poviat { Id = 323, Name = "grodziski", Province = ProvinceProvider.Get(15), Sanitize = "grodziski", Capital = "0" };
            yield return new Poviat { Id = 324, Name = "jarociński", Province = ProvinceProvider.Get(15), Sanitize = "jarocinski", Capital = "0" };
            yield return new Poviat { Id = 325, Name = "kaliski", Province = ProvinceProvider.Get(15), Sanitize = "kaliski", Capital = "2359" };
            yield return new Poviat { Id = 326, Name = "kępiński", Province = ProvinceProvider.Get(15), Sanitize = "kepinski", Capital = "0" };
            yield return new Poviat { Id = 327, Name = "kolski", Province = ProvinceProvider.Get(15), Sanitize = "kolski", Capital = "0" };
            yield return new Poviat { Id = 328, Name = "koniński", Province = ProvinceProvider.Get(15), Sanitize = "koninski", Capital = "2226" };
            yield return new Poviat { Id = 329, Name = "kościański", Province = ProvinceProvider.Get(15), Sanitize = "koscianski", Capital = "0" };
            yield return new Poviat { Id = 330, Name = "krotoszyński", Province = ProvinceProvider.Get(15), Sanitize = "krotoszynski", Capital = "0" };
            yield return new Poviat { Id = 331, Name = "leszczyński", Province = ProvinceProvider.Get(15), Sanitize = "leszczynski", Capital = "2227" };
            yield return new Poviat { Id = 332, Name = "międzychodzki", Province = ProvinceProvider.Get(15), Sanitize = "miedzychodzki", Capital = "0" };
            yield return new Poviat { Id = 333, Name = "nowotomyski", Province = ProvinceProvider.Get(15), Sanitize = "nowotomyski", Capital = "0" };
            yield return new Poviat { Id = 334, Name = "obornicki", Province = ProvinceProvider.Get(15), Sanitize = "obornicki", Capital = "0" };
            yield return new Poviat { Id = 335, Name = "ostrowski", Province = ProvinceProvider.Get(15), Sanitize = "ostrowski", Capital = "0" };
            yield return new Poviat { Id = 336, Name = "ostrzeszowski", Province = ProvinceProvider.Get(15), Sanitize = "ostrzeszowski", Capital = "0" };
            yield return new Poviat { Id = 337, Name = "pilski", Province = ProvinceProvider.Get(15), Sanitize = "pilski", Capital = "0" };
            yield return new Poviat { Id = 338, Name = "pleszewski", Province = ProvinceProvider.Get(15), Sanitize = "pleszewski", Capital = "0" };
            yield return new Poviat { Id = 339, Name = "poznański", Province = ProvinceProvider.Get(15), Sanitize = "poznanski", Capital = "2228" };
            yield return new Poviat { Id = 340, Name = "rawicki", Province = ProvinceProvider.Get(15), Sanitize = "rawicki", Capital = "0" };
            yield return new Poviat { Id = 341, Name = "słupecki", Province = ProvinceProvider.Get(15), Sanitize = "slupecki", Capital = "0" };
            yield return new Poviat { Id = 342, Name = "szamotulski", Province = ProvinceProvider.Get(15), Sanitize = "szamotulski", Capital = "0" };
            yield return new Poviat { Id = 343, Name = "średzki", Province = ProvinceProvider.Get(15), Sanitize = "sredzki", Capital = "0" };
            yield return new Poviat { Id = 344, Name = "śremski", Province = ProvinceProvider.Get(15), Sanitize = "sremski", Capital = "0" };
            yield return new Poviat { Id = 345, Name = "turecki", Province = ProvinceProvider.Get(15), Sanitize = "turecki", Capital = "0" };
            yield return new Poviat { Id = 346, Name = "wągrowiecki", Province = ProvinceProvider.Get(15), Sanitize = "wagrowiecki", Capital = "0" };
            yield return new Poviat { Id = 347, Name = "wolsztyński", Province = ProvinceProvider.Get(15), Sanitize = "wolsztynski", Capital = "0" };
            yield return new Poviat { Id = 348, Name = "wrzesiński", Province = ProvinceProvider.Get(15), Sanitize = "wrzesinski", Capital = "0" };
            yield return new Poviat { Id = 349, Name = "złotowski", Province = ProvinceProvider.Get(15), Sanitize = "zlotowski", Capital = "0" };
            yield return new Poviat { Id = 350, Name = "Kalisz m.", Province = ProvinceProvider.Get(15), Sanitize = "kalisz_miasto", Capital = "0" };
            yield return new Poviat { Id = 351, Name = "Konin m.", Province = ProvinceProvider.Get(15), Sanitize = "konin_miasto", Capital = "0" };
            yield return new Poviat { Id = 352, Name = "Leszno m.", Province = ProvinceProvider.Get(15), Sanitize = "leszno_miasto", Capital = "0" };
            yield return new Poviat { Id = 353, Name = "Poznań m.", Province = ProvinceProvider.Get(15), Sanitize = "poznan_miasto", Capital = "0" };
            yield return new Poviat { Id = 354, Name = "białogardzki", Province = ProvinceProvider.Get(16), Sanitize = "bialogardzki", Capital = "0" };
            yield return new Poviat { Id = 355, Name = "choszczeński", Province = ProvinceProvider.Get(16), Sanitize = "choszczenski", Capital = "0" };
            yield return new Poviat { Id = 356, Name = "drawski", Province = ProvinceProvider.Get(16), Sanitize = "drawski", Capital = "0" };
            yield return new Poviat { Id = 357, Name = "goleniowski", Province = ProvinceProvider.Get(16), Sanitize = "goleniowski", Capital = "0" };
            yield return new Poviat { Id = 358, Name = "gryficki", Province = ProvinceProvider.Get(16), Sanitize = "gryficki", Capital = "0" };
            yield return new Poviat { Id = 359, Name = "gryfiński", Province = ProvinceProvider.Get(16), Sanitize = "gryfinski", Capital = "0" };
            yield return new Poviat { Id = 360, Name = "kamieński", Province = ProvinceProvider.Get(16), Sanitize = "kamienski", Capital = "2334" };
            yield return new Poviat { Id = 361, Name = "kołobrzeski", Province = ProvinceProvider.Get(16), Sanitize = "kolobrzeski", Capital = "0" };
            yield return new Poviat { Id = 362, Name = "koszaliński", Province = ProvinceProvider.Get(16), Sanitize = "koszalinski", Capital = "2358" };
            yield return new Poviat { Id = 363, Name = "myśliborski", Province = ProvinceProvider.Get(16), Sanitize = "mysliborski", Capital = "0" };
            yield return new Poviat { Id = 364, Name = "policki", Province = ProvinceProvider.Get(16), Sanitize = "policki", Capital = "0" };
            yield return new Poviat { Id = 365, Name = "pyrzycki", Province = ProvinceProvider.Get(16), Sanitize = "pyrzycki", Capital = "0" };
            yield return new Poviat { Id = 366, Name = "sławieński", Province = ProvinceProvider.Get(16), Sanitize = "slawienski", Capital = "0" };
            yield return new Poviat { Id = 367, Name = "stargardzki", Province = ProvinceProvider.Get(16), Sanitize = "stargardzki", Capital = "0" };
            yield return new Poviat { Id = 368, Name = "szczecinecki", Province = ProvinceProvider.Get(16), Sanitize = "szczecinecki", Capital = "0" };
            yield return new Poviat { Id = 369, Name = "świdwiński", Province = ProvinceProvider.Get(16), Sanitize = "swidwinski", Capital = "0" };
            yield return new Poviat { Id = 370, Name = "wałecki", Province = ProvinceProvider.Get(16), Sanitize = "walecki", Capital = "0" };
            yield return new Poviat { Id = 371, Name = "Koszalin m.", Province = ProvinceProvider.Get(16), Sanitize = "koszalin_miasto", Capital = "0" };
            yield return new Poviat { Id = 372, Name = "Szczecin m.", Province = ProvinceProvider.Get(16), Sanitize = "szczecin_miasto", Capital = "0" };
            yield return new Poviat { Id = 373, Name = "Świnoujście m.", Province = ProvinceProvider.Get(16), Sanitize = "swinoujscie_miasto", Capital = "0" };
            yield return new Poviat { Id = 374, Name = "brzeziński", Province = ProvinceProvider.Get(5), Sanitize = "brzezinski", Capital = "0" };
            yield return new Poviat { Id = 375, Name = "wschowski", Province = ProvinceProvider.Get(4), Sanitize = "wschowski", Capital = "0" };
            yield return new Poviat { Id = 377, Name = "leski", Province = ProvinceProvider.Get(9), Sanitize = "leski", Capital = "0" };
            yield return new Poviat { Id = 378, Name = "sztumski", Province = ProvinceProvider.Get(11), Sanitize = "sztumski", Capital = "0" };
            yield return new Poviat { Id = 379, Name = "węgorzewski", Province = ProvinceProvider.Get(14), Sanitize = "wegorzewski", Capital = "0" };
            yield return new Poviat { Id = 380, Name = "gołdapski", Province = ProvinceProvider.Get(14), Sanitize = "goldapski", Capital = "0" };
            yield return new Poviat { Id = 381, Name = "łobeski", Province = ProvinceProvider.Get(16), Sanitize = "lobeski", Capital = "0" };
        }

        // Hot to cold collection
        private static readonly IEnumerable<Poviat> Poviats = GetPoviats().ToList();

        internal static Poviat Get(int id)
        {
            return Poviats.SingleOrDefault(x => x.Id == id);
        }
    }
}
