// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Trader.Web.Controllers {
    public partial class DomiportaRPUrlMapController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DomiportaRPUrlMapController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DomiportaRPUrlMapController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PerformSearch() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PerformSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PerformSearchSeo() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PerformSearchSeo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SearchRss() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SearchRss);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ShowMap() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ShowMap);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ShowOnOnePage() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ShowOnOnePage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Show() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Show);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ShowPrint() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ShowPrint);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ShowInvestments() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ShowInvestments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SearchCategories() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SearchCategories);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DomiportaRPUrlMapController Actions { get { return MVC.DomiportaRPUrlMap; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "DomiportaRPUrlMap";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "DomiportaRPUrlMap";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string PerformSearch = "PerformSearch";
            public readonly string PerformSearchSeo = "PerformSearchSeo";
            public readonly string SearchRss = "SearchRss";
            public readonly string ShowMap = "ShowMap";
            public readonly string ShowOnOnePage = "ShowOnOnePage";
            public readonly string Show = "Show";
            public readonly string ShowPrint = "ShowPrint";
            public readonly string ShowInvestments = "ShowInvestments";
            public readonly string SearchCategories = "SearchCategories";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string PerformSearch = "PerformSearch";
            public const string PerformSearchSeo = "PerformSearchSeo";
            public const string SearchRss = "SearchRss";
            public const string ShowMap = "ShowMap";
            public const string ShowOnOnePage = "ShowOnOnePage";
            public const string Show = "Show";
            public const string ShowPrint = "ShowPrint";
            public const string ShowInvestments = "ShowInvestments";
            public const string SearchCategories = "SearchCategories";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_DomiportaRPUrlMapController: Trader.Web.Controllers.DomiportaRPUrlMapController {
        public T4MVC_DomiportaRPUrlMapController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult PerformSearch(Trader.Web.Models.DomiportaRP.DomiportaRPSearchViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PerformSearch);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PerformSearchSeo(Trader.Web.Models.DomiportaRP.DomiportaRPSearchViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PerformSearchSeo);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SearchRss(Trader.Web.Models.DomiportaRP.DomiportaRPSearchViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SearchRss);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ShowMap(Trader.Web.Models.DomiportaRP.DomiportaRPInvestmentViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowMap);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ShowOnOnePage(Trader.Web.Models.DomiportaRP.DomiportaRPInvestmentViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowOnOnePage);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Show(Trader.Web.Models.DomiportaRP.DomiportaRPInvestmentViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Show);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ShowPrint(Trader.Web.Models.DomiportaRP.DomiportaRPInvestmentViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowPrint);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ShowInvestments(Trader.Web.Models.DomiportaRP.DomiportaRPInvestmentViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowInvestments);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SearchCategories(Trader.Web.Models.DomiportaRP.DomiportaRPCategorySearchViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SearchCategories);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
