// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Trader.Web.Controllers {
    public partial class DomiportaController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DomiportaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Details() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DetailsWithCategory() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DetailsWithCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult InvestmentIISMapping() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.InvestmentIISMapping);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Investment() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Investment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SearchResult() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SearchResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SearchResultPrimaryMarket() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultPrimaryMarket);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SearchResultSecondaryMarket() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultSecondaryMarket);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SearchResultGuessMarketIISRedirect() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultGuessMarketIISRedirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SearchResultGuessMarket() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultGuessMarket);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Gallery() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Gallery);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DomiportaController Actions { get { return MVC.Domiporta; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Domiporta";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Domiporta";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Details = "Details";
            public readonly string RedirectToHP = "RedirectToHP";
            public readonly string DetailsWithCategory = "DetailsWithCategory";
            public readonly string WebRedirect = "WebRedirect";
            public readonly string InvestmentIISMapping = "InvestmentIISMapping";
            public readonly string Investment = "Investment";
            public readonly string SearchResult = "SearchResult";
            public readonly string SearchResultPrimaryMarket = "SearchResultPrimaryMarket";
            public readonly string SearchResultSecondaryMarket = "SearchResultSecondaryMarket";
            public readonly string SearchResultGuessMarketIISRedirect = "SearchResultGuessMarketIISRedirect";
            public readonly string SearchResultGuessMarket = "SearchResultGuessMarket";
            public readonly string Gallery = "Gallery";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Details = "Details";
            public const string RedirectToHP = "RedirectToHP";
            public const string DetailsWithCategory = "DetailsWithCategory";
            public const string WebRedirect = "WebRedirect";
            public const string InvestmentIISMapping = "InvestmentIISMapping";
            public const string Investment = "Investment";
            public const string SearchResult = "SearchResult";
            public const string SearchResultPrimaryMarket = "SearchResultPrimaryMarket";
            public const string SearchResultSecondaryMarket = "SearchResultSecondaryMarket";
            public const string SearchResultGuessMarketIISRedirect = "SearchResultGuessMarketIISRedirect";
            public const string SearchResultGuessMarket = "SearchResultGuessMarket";
            public const string Gallery = "Gallery";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string WebRedirect = "~/Views/Domiporta/WebRedirect.cshtml";
            public readonly string WebRedirect_Mobile = "~/Views/Domiporta/WebRedirect.Mobile.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_DomiportaController: Trader.Web.Controllers.DomiportaController {
        public T4MVC_DomiportaController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Details(Trader.Web.Models.Domiporta.WebDetailsViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Details);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RedirectToHP() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RedirectToHP);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DetailsWithCategory(Trader.Web.Models.Domiporta.WebAdvertViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DetailsWithCategory);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult WebRedirect() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.WebRedirect);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult InvestmentIISMapping(Trader.Web.Models.Domiporta.WebInvestmentIISMappingViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.InvestmentIISMapping);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Investment(Trader.Web.Models.Domiporta.WebInvestmentViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Investment);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SearchResult(Trader.Web.Models.Domiporta.WebSearchResultViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SearchResult);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SearchResultPrimaryMarket(Trader.Web.Models.Domiporta.WebSearchResultViewModelPrimaryMarket viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultPrimaryMarket);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SearchResultSecondaryMarket(Trader.Web.Models.Domiporta.WebSearchResultViewModelSecondaryMarket viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultSecondaryMarket);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SearchResultGuessMarketIISRedirect(Trader.Web.Models.Domiporta.GuessMarketViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultGuessMarketIISRedirect);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SearchResultGuessMarket(object viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SearchResultGuessMarket);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Gallery(Trader.Web.Models.Domiporta.WebGalleryViewModel viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Gallery);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
