// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.
 
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Layout_AndroidLess22 = "~/Views/Shared/_Layout.AndroidLess22.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _Layout_Mobile = "~/Views/Shared/_Layout.Mobile.cshtml";
            public readonly string _Layout_WeakMobile = "~/Views/Shared/_Layout.WeakMobile.cshtml";
            public readonly string _ViewSwitcher = "~/Views/Shared/_ViewSwitcher.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string ErrorHandler = "~/Views/Shared/ErrorHandler.cshtml";
            public readonly string Footer_Mobile = "~/Views/Shared/Footer.Mobile.cshtml";
            public readonly string GroupedSearchResultList_Mobile = "~/Views/Shared/GroupedSearchResultList.Mobile.cshtml";
            public readonly string Header_Mobile = "~/Views/Shared/Header.Mobile.cshtml";
            public readonly string SetNotMobileCookie = "~/Views/Shared/SetNotMobileCookie.cshtml";
            static readonly _AdServer s_AdServer = new _AdServer();
            public _AdServer AdServer { get { return s_AdServer; } }
            public partial class _AdServer{
                public readonly string AdServerBody = "~/Views/Shared/AdServer/AdServerBody.cshtml";
                public readonly string AdServerColumnBottom = "~/Views/Shared/AdServer/AdServerColumnBottom.cshtml";
                public readonly string AdServerColumnMiddle = "~/Views/Shared/AdServer/AdServerColumnMiddle.cshtml";
                public readonly string AdServerColumnTop = "~/Views/Shared/AdServer/AdServerColumnTop.cshtml";
                public readonly string AdServerHead = "~/Views/Shared/AdServer/AdServerHead.cshtml";
            }
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string CreationDate = "CreationDate";
                public readonly string Date = "Date";
                public readonly string Decimal = "Decimal";
                public readonly string Email = "Email";
                public readonly string Integer = "Integer";
                public readonly string Phone = "Phone";
            }
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string GlossaryAsRadio = "GlossaryAsRadio";
                public readonly string GlossaryBase = "GlossaryBase";
                public readonly string GlossaryFilter = "GlossaryFilter";
                public readonly string RangeCriteria = "RangeCriteria";
            }
            static readonly _Google s_Google = new _Google();
            public _Google Google { get { return s_Google; } }
            public partial class _Google{
                public readonly string GoogleAnalyticsJavascriptVersion = "~/Views/Shared/Google/GoogleAnalyticsJavascriptVersion.cshtml";
                public readonly string GoogleAnalyticsMobileVersion = "~/Views/Shared/Google/GoogleAnalyticsMobileVersion.cshtml";
            }
            static readonly _JavaScriptInlineCode s_JavaScriptInlineCode = new _JavaScriptInlineCode();
            public _JavaScriptInlineCode JavaScriptInlineCode { get { return s_JavaScriptInlineCode; } }
            public partial class _JavaScriptInlineCode{
                public readonly string FormatInt = "~/Views/Shared/JavaScriptInlineCode/FormatInt.cshtml";
            }
            static readonly _Quartic s_Quartic = new _Quartic();
            public _Quartic Quartic { get { return s_Quartic; } }
            public partial class _Quartic{
                public readonly string QuarticDetails = "~/Views/Shared/Quartic/QuarticDetails.cshtml";
                public readonly string QuarticForHP = "~/Views/Shared/Quartic/QuarticForHP.cshtml";
                public readonly string QuarticForSearch = "~/Views/Shared/Quartic/QuarticForSearch.cshtml";
                public readonly string QuarticIndexParams = "~/Views/Shared/Quartic/QuarticIndexParams.cshtml";
                public readonly string QuarticProtocol = "~/Views/Shared/Quartic/QuarticProtocol.cshtml";
                public readonly string QuarticResults = "~/Views/Shared/Quartic/QuarticResults.cshtml";
                public readonly string QuarticSearchParams = "~/Views/Shared/Quartic/QuarticSearchParams.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
